# Contents of file "centos7-container.def"
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

# The default command to run once our image is finished.
%runscript
    Rscript $@
    
# Installing the software in our image.
%post
    yum -y install epel-release
    yum -y install R
    yum -y install git
    git clone https://github.com/UW-GAC/analysis_pipeline.git
    cd analysis_pipeline
    Rscript install_packages.R
    # Rscript -e 'if (! require(rstan)) install.packages("rstan", repo="http://cran.rstudio.com/")'

# Command
%test
    Rscript -e 'library(GENESIS)'
