# Contents of file "centos7-container.def"
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

# The default command to run once our image is finished.
%runscript
    Rscript $@
    
# Installing the software in our image.
%post
    yum -y install epel-release
    yum -y install R
    yum -y install git
    yum -y install bcftools
    yum -y install wget
    yum -y install unzip
    yum -y install tar
    yum -y install gzip
    echo "export PATH=$HOME/bin:$PATH" > .bashrc
    mkdir bin
    cd bin
    wget http://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20201019.zip
    unzip plink_linux_x86_64_20201019.zip
    wget http://people.virginia.edu/~wc9c/KING/Linux-king.tar.gz
    tar -xzvf Linux-king.tar.gz
    cd ..
    git clone https://github.com/UW-GAC/analysis_pipeline.git
    cd analysis_pipeline
    Rscript install_packages.R
    # Rscript -e 'if (! require(rstan)) install.packages("rstan", repo="http://cran.rstudio.com/")'

# Command
%test
    Rscript -e 'library(GENESIS)'
